import { ReactComponent as cartIcon } from '../../assets/cart.svg';
import { ReactComponent as shekelIcon } from '../../assets/shekel.svg';

export const config = [
	{
		id: 1,
		text: 'SIGN IN',
		backgroundColor: '',
		textColor: '',
		state: 'disable',
		sizeW: 'fill',
		size: 'large',
	},
	{
		id: 2,
		text: 'SIGN IN',
		backgroundColor: 'dark',
		textColor: 'white',
		state: 'enable',
		sizeW: 'fill',
		size: 'large',
	},
	{
		id: 3,
		text: 'SEARCH',
		backgroundColor: '',
		textColor: '',
		state: 'disable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 4,
		text: 'SEARCH',
		backgroundColor: 'dark',
		textColor: 'white',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 5,
		text: 'CART',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
		Icon: cartIcon,
		iconPosition: 'before',
		nums: 1,
	},
	{
		id: 6,
		text: 'Done',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'small',
	},
	{
		id: 7,
		text: 'Back',
		backgroundColor: 'light',
		textColor: 'black',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 8,
		text: 'Next',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 9,
		text: 'MAKE ORDER',
		backgroundColor: 'dark',
		textColor: 'white',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 10,
		text: 'Price: 3090',
		backgroundColor: 'light',
		textColor: 'black',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
		Icon: shekelIcon,
		iconPosition: 'after',
		rounded: true,
	},
	{
		id: 11,
		text: 'Repay',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 12,
		text: 'Black list',
		backgroundColor: 'light',
		textColor: 'black',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 13,
		text: 'Cancel',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 14,
		text: 'Done',
		backgroundColor: 'light',
		textColor: 'black',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 15,
		text: 'Wait for a confirmation',
		backgroundColor: 'light',
		textColor: 'green',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 16,
		text: 'Find another',
		backgroundColor: 'light',
		textColor: 'black',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 17,
		text: 'Edit absence',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 18,
		text: 'Absence',
		backgroundColor: 'light',
		textColor: 'blue',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 19,
		text: 'Add review',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 20,
		text: 'Confirm',
		backgroundColor: 'light',
		textColor: 'green',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
	{
		id: 21,
		text: 'Edit review',
		backgroundColor: 'light',
		textColor: 'pink',
		state: 'enable',
		sizeW: 'fixed',
		size: 'medium',
	},
];
